Metrics/LineLength:
  Max: 250

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 50

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent